# Generated by Django 4.1.3 on 2022-11-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tage', models.IntegerField(default=0)),
                ('tphoneno', models.IntegerField(default=0)),
                ('temail', models.CharField(max_length=50)),
                ('tcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.city')),
                ('tcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_No', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Trainer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.trainer_reg')),
            ],
        ),
    ]
